import { GeistSans } from 'geist/font/sans'
// or if you want the mono variant
// import { GeistMono } from 'geist/font/mono'
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={GeistSans.className}>
      <body>{children}</body>
    </html>
  );
}
